-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.email_verification
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    authentication character varying(150) NOT NULL,
    email character varying(150) NOT NULL UNIQUE,
    is_approved boolean NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    telephone_no character(11) NOT NULL,
    web_address character varying(150) NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.hrms_employees_verification
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    is_approved boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position_names
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 78 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_name character varying(100) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seeker_id integer NOT NULL,
    firstname character varying(30) NOT NULL,
    lastname character varying(50) NOT NULL,
    tc_no character(11) NOT NULL UNIQUE,
    birth_year date NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public.mernis_verification
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_approved boolean NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_employees
(
    employees_id integer NOT NULL,
    firstname character varying(30) NOT NULL,
    lastname character varying(50) NOT NULL,
    PRIMARY KEY (employees_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 78 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    email character varying(150) NOT NULL UNIQUE,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (job_seeker_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_employees
    ADD FOREIGN KEY (employees_id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.mernis_verification
    ADD FOREIGN KEY (id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.email_verification
    ADD FOREIGN KEY (id)
        REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.hrms_employees_verification
    ADD FOREIGN KEY (id)
        REFERENCES public.users (id)
    NOT VALID;

END;