-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.advertisements
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    application_deadline date NOT NULL,
    creation_date date NOT NULL,
    is_advertisement_open boolean NOT NULL,
    job_description character varying(255) NOT NULL,
    max_salary double precision,
    min_salary double precision,
    number_of_open_position integer NOT NULL,
    city_id integer NOT NULL,
    job_position_id integer NOT NULL,
    work_type_id integer NOT NULL,
    work_time_id integer NOT NULL,
    is_approved boolean NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    city_name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cvs
(
    cv_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cover_letter character varying(255),
    user_id integer NOT NULL,
    creation_date date,
    PRIMARY KEY (cv_id)
);

CREATE TABLE public.educations
(
    education_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at date NOT NULL,
    school_department_name character varying(255) NOT NULL,
    school_graduation_date date,
    school_name character varying(255) NOT NULL,
    school_start_date date NOT NULL,
    cv_id integer NOT NULL,
    PRIMARY KEY (education_id)
);

CREATE TABLE public.email_verifications
(
    email_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    authentication character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    is_approved boolean NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (email_id)
);

CREATE TABLE public.employers
(
    company_name character varying(255) NOT NULL,
    telephone_no character varying(11) NOT NULL,
    web_address character varying(255) NOT NULL,
    user_id integer NOT NULL,
    is_active boolean NOT NULL,
    is_approved boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.experiences
(
    experience_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    business_leaving_date date,
    business_name character varying(255) NOT NULL,
    business_start_date date NOT NULL,
    created_at date,
    is_still_working boolean NOT NULL,
    job_position_name character varying(255) NOT NULL,
    cv_id integer NOT NULL,
    PRIMARY KEY (experience_id)
);

CREATE TABLE public.hrms_employees
(
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_date date,
    is_active_position boolean NOT NULL,
    is_deleted_position boolean NOT NULL,
    job_name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    birth_year integer NOT NULL,
    firstname character varying(255) NOT NULL,
    lastname character varying(255) NOT NULL,
    tc_no character varying(11) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.languages
(
    language_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at date NOT NULL,
    language_level_number integer NOT NULL,
    language_name character varying(255) NOT NULL,
    cv_id integer NOT NULL,
    PRIMARY KEY (language_id)
);

CREATE TABLE public.mernis_verifications
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    approval_date timestamp without time zone NOT NULL,
    created_at date NOT NULL,
    is_approved boolean NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.photos
(
    photo_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    photo_url character varying(255) NOT NULL,
    cv_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (photo_id)
);

CREATE TABLE public.programming_skills
(
    skill_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at date NOT NULL,
    programming_name character varying(255) NOT NULL,
    programming_skill_level integer NOT NULL,
    cv_id integer,
    PRIMARY KEY (skill_id)
);

CREATE TABLE public.social_medias
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at date NOT NULL,
    social_media_name character varying(255) NOT NULL,
    social_media_url character varying(255) NOT NULL,
    cv_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    confirm_password character varying(255) NOT NULL,
    created_date date NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    is_system_user boolean,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.work_time_features
(
    work_time_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    work_time_name character varying(255) NOT NULL,
    PRIMARY KEY (work_time_id)
);

CREATE TABLE public.work_type_features
(
    work_type_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    work_type_name character varying(255) NOT NULL,
    PRIMARY KEY (work_type_id)
);

ALTER TABLE public.advertisements
    ADD FOREIGN KEY (work_type_id)
    REFERENCES public.work_type_features (work_type_id)
    NOT VALID;


ALTER TABLE public.advertisements
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.advertisements
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.advertisements
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.advertisements
    ADD FOREIGN KEY (work_time_id)
    REFERENCES public.work_time_features (work_time_id)
    NOT VALID;


ALTER TABLE public.cvs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.educations
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.email_verifications
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.hrms_employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.mernis_verifications
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (user_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.programming_skills
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;


ALTER TABLE public.social_medias
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cvs (cv_id)
    NOT VALID;

END;